version: 2.1

orbs:
  bridgecrew: bridgecrew/bridgecrew@1.0.5

jobs:
  checkov:
    docker:
      - image: bridgecrew/checkov:latest
    working_directory: /tmp/workspace
    environment:
      ENV_FILE: /tmp/workspace/
      DOCKER_BUILDKIT: "1"
      BUILDKIT_PROGRESS: plain
    steps:
      - checkout
      - attach_workspace:
         at: /tmp/workspace

      - run:
          name: Install checkov
          command: |
           sudo apt update
           pip install -U checkov
         
      #- run:
      #    name: Dockerfile Static Scanning
      #    command: |
      #      checkov -d . --bc-api-key $CHECKOV --repo-id $CIRCLE_PROJECT_REPONAME --branch $CIRCLE_BRANCH

      - run:
          name: Run Checkov
          command: |
            export BC_API_KEY=$BC_API_KEY 
            export REPO_ID=$CIRCLE_PROJECT_REPONAME
            export BRANCH=$CIRCLE_BRANCH
            checkov -d . --bc-api-key $BC_API_KEY --repo-id $REPO_ID --branch $BRANCH            

workflows:
  version: 2
  checkov:
    jobs:
      - checkov:
         context: McCain-dev